/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculatorswingapp;

/**
 *
 * @author Eagle
 */
public class CalcForm extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public CalcForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ResultLine = new javax.swing.JPanel();
        ResultLabel = new javax.swing.JLabel();
        FirstLine = new javax.swing.JPanel();
        Num1 = new javax.swing.JButton();
        Num2 = new javax.swing.JButton();
        Num3 = new javax.swing.JButton();
        Plus = new javax.swing.JButton();
        SecondLine = new javax.swing.JPanel();
        Num4 = new javax.swing.JButton();
        Num5 = new javax.swing.JButton();
        Num6 = new javax.swing.JButton();
        Minus = new javax.swing.JButton();
        ThirdLine = new javax.swing.JPanel();
        Num7 = new javax.swing.JButton();
        Num8 = new javax.swing.JButton();
        Num9 = new javax.swing.JButton();
        Multiply = new javax.swing.JButton();
        FourthLine = new javax.swing.JPanel();
        Dot = new javax.swing.JButton();
        Num0 = new javax.swing.JButton();
        Equal = new javax.swing.JButton();
        Divide = new javax.swing.JButton();
        FifthLine = new javax.swing.JPanel();
        DefaultButton = new javax.swing.JButton();
        LeftPar = new javax.swing.JButton();
        RightPar = new javax.swing.JButton();
        NoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(300, 300));
        setMinimumSize(new java.awt.Dimension(300, 300));
        setPreferredSize(new java.awt.Dimension(300, 300));
        setSize(new java.awt.Dimension(300, 300));
        getContentPane().setLayout(new java.awt.GridLayout(6, 0));

        ResultLine.setBackground(new java.awt.Color(255, 255, 255));
        ResultLine.setToolTipText("");
        ResultLine.setAlignmentX(0.0F);
        ResultLine.setAutoscrolls(true);
        ResultLine.setMaximumSize(new java.awt.Dimension(300, 50));
        ResultLine.setMinimumSize(new java.awt.Dimension(300, 50));
        ResultLine.setPreferredSize(new java.awt.Dimension(300, 50));

        javax.swing.GroupLayout ResultLineLayout = new javax.swing.GroupLayout(ResultLine);
        ResultLine.setLayout(ResultLineLayout);
        ResultLineLayout.setHorizontalGroup(
            ResultLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ResultLabel)
        );
        ResultLineLayout.setVerticalGroup(
            ResultLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ResultLabel)
        );

        getContentPane().add(ResultLine);
        ResultLine.getAccessibleContext().setAccessibleName("");

        FirstLine.setAlignmentX(0.0F);
        FirstLine.setAlignmentY(1.0F);
        FirstLine.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        FirstLine.setMaximumSize(new java.awt.Dimension(300, 50));
        FirstLine.setMinimumSize(new java.awt.Dimension(300, 50));
        FirstLine.setName(""); // NOI18N
        FirstLine.setPreferredSize(new java.awt.Dimension(300, 50));
        FirstLine.setLayout(new java.awt.GridLayout());

        Num1.setText("1");
        Num1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Num1MouseReleased(evt);
            }
        });
        Num1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Num1KeyReleased(evt);
            }
        });
        FirstLine.add(Num1);

        Num2.setText("2");
        Num2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Num2MouseReleased(evt);
            }
        });
        Num2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Num2KeyReleased(evt);
            }
        });
        FirstLine.add(Num2);

        Num3.setText("3");
        Num3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Num3MouseReleased(evt);
            }
        });
        Num3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Num3KeyReleased(evt);
            }
        });
        FirstLine.add(Num3);

        Plus.setText("+");
        Plus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                PlusMouseReleased(evt);
            }
        });
        Plus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PlusKeyReleased(evt);
            }
        });
        FirstLine.add(Plus);

        getContentPane().add(FirstLine);
        FirstLine.getAccessibleContext().setAccessibleName("");

        SecondLine.setMaximumSize(new java.awt.Dimension(300, 50));
        SecondLine.setMinimumSize(new java.awt.Dimension(300, 50));
        SecondLine.setPreferredSize(new java.awt.Dimension(300, 50));
        SecondLine.setLayout(new java.awt.GridLayout());

        Num4.setText("4");
        SecondLine.add(Num4);

        Num5.setText("5");
        SecondLine.add(Num5);

        Num6.setText("6");
        SecondLine.add(Num6);

        Minus.setText("-");
        SecondLine.add(Minus);

        getContentPane().add(SecondLine);

        ThirdLine.setMaximumSize(new java.awt.Dimension(300, 50));
        ThirdLine.setMinimumSize(new java.awt.Dimension(300, 50));
        ThirdLine.setPreferredSize(new java.awt.Dimension(300, 50));
        ThirdLine.setLayout(new java.awt.GridLayout());

        Num7.setText("7");
        ThirdLine.add(Num7);

        Num8.setText("8");
        Num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num8ActionPerformed(evt);
            }
        });
        ThirdLine.add(Num8);

        Num9.setText("9");
        ThirdLine.add(Num9);

        Multiply.setText("*");
        ThirdLine.add(Multiply);

        getContentPane().add(ThirdLine);

        FourthLine.setMaximumSize(new java.awt.Dimension(300, 50));
        FourthLine.setMinimumSize(new java.awt.Dimension(300, 50));
        FourthLine.setPreferredSize(new java.awt.Dimension(300, 50));
        FourthLine.setLayout(new java.awt.GridLayout());

        Dot.setText(".");
        FourthLine.add(Dot);

        Num0.setText("0");
        FourthLine.add(Num0);

        Equal.setText("=");
        FourthLine.add(Equal);

        Divide.setText("/");
        FourthLine.add(Divide);

        getContentPane().add(FourthLine);

        FifthLine.setMaximumSize(new java.awt.Dimension(300, 50));
        FifthLine.setPreferredSize(new java.awt.Dimension(300, 50));
        FifthLine.setLayout(new java.awt.GridLayout());

        DefaultButton.setText("C");
        FifthLine.add(DefaultButton);

        LeftPar.setText("(");
        FifthLine.add(LeftPar);

        RightPar.setText(")");
        FifthLine.add(RightPar);
        FifthLine.add(NoButton);

        getContentPane().add(FifthLine);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Num8ActionPerformed

    private void Num1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Num1MouseReleased
        // TODO add your handling code here:
        setResultText(num1);
    }//GEN-LAST:event_Num1MouseReleased

    private void Num1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Num1KeyReleased
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if(ch == '1') {
            setResultText(num1);
        }
    }//GEN-LAST:event_Num1KeyReleased

    private void Num2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Num2KeyReleased
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if(ch == '2') {
            setResultText(num2);
        }
    }//GEN-LAST:event_Num2KeyReleased

    private void Num2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Num2MouseReleased
        // TODO add your handling code here:
        setResultText(num2);
    }//GEN-LAST:event_Num2MouseReleased

    private void Num3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Num3KeyReleased
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if(ch == '3') {
            setResultText(num3);
        }
    }//GEN-LAST:event_Num3KeyReleased

    private void Num3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Num3MouseReleased
        // TODO add your handling code here:
        setResultText(num3);
    }//GEN-LAST:event_Num3MouseReleased

    private void PlusKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PlusKeyReleased
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if(ch == '+') {
            setResultText(plus);
        }
    }//GEN-LAST:event_PlusKeyReleased

    private void PlusMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlusMouseReleased
        // TODO add your handling code here:
        setResultText(plus);
    }//GEN-LAST:event_PlusMouseReleased

    private void setResultText(String s) {
        String currText = ResultLabel.getText();
        ResultLabel.setText(currText + s);
    }
    
    private final String num1 = "1";
    private final String num2 = "2";
    private final String num3 = "3";
    private final String num4 = "4";
    private final String num5 = "5";
    private final String num6 = "6";
    private final String num7 = "7";
    private final String num8 = "8";
    private final String num9 = "9";
    private final String num0 = "0";
    
    private final String plus = "+";
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DefaultButton;
    private javax.swing.JButton Divide;
    private javax.swing.JButton Dot;
    private javax.swing.JButton Equal;
    private javax.swing.JPanel FifthLine;
    private javax.swing.JPanel FirstLine;
    private javax.swing.JPanel FourthLine;
    private javax.swing.JButton LeftPar;
    private javax.swing.JButton Minus;
    private javax.swing.JButton Multiply;
    private javax.swing.JButton NoButton;
    private javax.swing.JButton Num0;
    private javax.swing.JButton Num1;
    private javax.swing.JButton Num2;
    private javax.swing.JButton Num3;
    private javax.swing.JButton Num4;
    private javax.swing.JButton Num5;
    private javax.swing.JButton Num6;
    private javax.swing.JButton Num7;
    private javax.swing.JButton Num8;
    private javax.swing.JButton Num9;
    private javax.swing.JButton Plus;
    private javax.swing.JLabel ResultLabel;
    private javax.swing.JPanel ResultLine;
    private javax.swing.JButton RightPar;
    private javax.swing.JPanel SecondLine;
    private javax.swing.JPanel ThirdLine;
    // End of variables declaration//GEN-END:variables
}
