/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculatorswingapp;

/**
 *
 * @author Eagle
 */
public class CalcForm extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public CalcForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ResultLine = new javax.swing.JPanel();
        ResultLabel = new javax.swing.JLabel();
        FirstLine = new javax.swing.JPanel();
        Num1 = new javax.swing.JButton();
        Num2 = new javax.swing.JButton();
        Num3 = new javax.swing.JButton();
        Plus = new javax.swing.JButton();
        SecondLine = new javax.swing.JPanel();
        Num4 = new javax.swing.JButton();
        Num5 = new javax.swing.JButton();
        Num6 = new javax.swing.JButton();
        Minus = new javax.swing.JButton();
        ThirdLine = new javax.swing.JPanel();
        Num7 = new javax.swing.JButton();
        Num8 = new javax.swing.JButton();
        Num9 = new javax.swing.JButton();
        Multiply = new javax.swing.JButton();
        FourthLine = new javax.swing.JPanel();
        Dot = new javax.swing.JButton();
        Num0 = new javax.swing.JButton();
        Equal = new javax.swing.JButton();
        Divide = new javax.swing.JButton();
        FifthLine = new javax.swing.JPanel();
        DefaultButton = new javax.swing.JButton();
        LeftPar = new javax.swing.JButton();
        RightPar = new javax.swing.JButton();
        NoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(350, 350));
        setMinimumSize(new java.awt.Dimension(350, 350));
        setPreferredSize(new java.awt.Dimension(350, 350));
        setResizable(false);
        setSize(new java.awt.Dimension(350, 350));
        getContentPane().setLayout(new java.awt.GridLayout(6, 0));

        ResultLine.setBackground(new java.awt.Color(255, 255, 255));
        ResultLine.setToolTipText("");
        ResultLine.setAlignmentX(0.0F);
        ResultLine.setAutoscrolls(true);
        ResultLine.setMaximumSize(new java.awt.Dimension(300, 50));
        ResultLine.setMinimumSize(new java.awt.Dimension(300, 50));
        ResultLine.setPreferredSize(new java.awt.Dimension(300, 50));
        ResultLine.setLayout(new javax.swing.BoxLayout(ResultLine, javax.swing.BoxLayout.LINE_AXIS));

        ResultLabel.setText("Calculator result: ");
        ResultLine.add(ResultLabel);

        getContentPane().add(ResultLine);
        ResultLine.getAccessibleContext().setAccessibleName("");

        FirstLine.setAlignmentX(0.0F);
        FirstLine.setAlignmentY(1.0F);
        FirstLine.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        FirstLine.setMaximumSize(new java.awt.Dimension(450, 50));
        FirstLine.setMinimumSize(new java.awt.Dimension(450, 50));
        FirstLine.setName(""); // NOI18N
        FirstLine.setPreferredSize(new java.awt.Dimension(450, 50));
        FirstLine.setLayout(new java.awt.GridLayout(1, 0));

        Num1.setText("1");
        FirstLine.add(Num1);

        Num2.setText("2");
        FirstLine.add(Num2);

        Num3.setText("3");
        FirstLine.add(Num3);

        Plus.setText("+");
        FirstLine.add(Plus);

        getContentPane().add(FirstLine);
        FirstLine.getAccessibleContext().setAccessibleName("");

        SecondLine.setLayout(new java.awt.GridLayout(1, 0));

        Num4.setText("4");
        SecondLine.add(Num4);

        Num5.setText("5");
        SecondLine.add(Num5);

        Num6.setText("6");
        SecondLine.add(Num6);

        Minus.setText("-");
        SecondLine.add(Minus);

        getContentPane().add(SecondLine);

        ThirdLine.setLayout(new java.awt.GridLayout(1, 0));

        Num7.setText("7");
        ThirdLine.add(Num7);

        Num8.setText("8");
        Num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num8ActionPerformed(evt);
            }
        });
        ThirdLine.add(Num8);

        Num9.setText("9");
        ThirdLine.add(Num9);

        Multiply.setText("*");
        ThirdLine.add(Multiply);

        getContentPane().add(ThirdLine);

        FourthLine.setLayout(new java.awt.GridLayout(1, 0));

        Dot.setText(".");
        FourthLine.add(Dot);

        Num0.setText("0");
        FourthLine.add(Num0);

        Equal.setText("=");
        FourthLine.add(Equal);

        Divide.setText("/");
        FourthLine.add(Divide);

        getContentPane().add(FourthLine);

        FifthLine.setLayout(new java.awt.GridLayout(1, 0));

        DefaultButton.setText("C");
        FifthLine.add(DefaultButton);

        LeftPar.setText("(");
        FifthLine.add(LeftPar);

        RightPar.setText(")");
        FifthLine.add(RightPar);
        FifthLine.add(NoButton);

        getContentPane().add(FifthLine);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Num8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DefaultButton;
    private javax.swing.JButton Divide;
    private javax.swing.JButton Dot;
    private javax.swing.JButton Equal;
    private javax.swing.JPanel FifthLine;
    private javax.swing.JPanel FirstLine;
    private javax.swing.JPanel FourthLine;
    private javax.swing.JButton LeftPar;
    private javax.swing.JButton Minus;
    private javax.swing.JButton Multiply;
    private javax.swing.JButton NoButton;
    private javax.swing.JButton Num0;
    private javax.swing.JButton Num1;
    private javax.swing.JButton Num2;
    private javax.swing.JButton Num3;
    private javax.swing.JButton Num4;
    private javax.swing.JButton Num5;
    private javax.swing.JButton Num6;
    private javax.swing.JButton Num7;
    private javax.swing.JButton Num8;
    private javax.swing.JButton Num9;
    private javax.swing.JButton Plus;
    private javax.swing.JLabel ResultLabel;
    private javax.swing.JPanel ResultLine;
    private javax.swing.JButton RightPar;
    private javax.swing.JPanel SecondLine;
    private javax.swing.JPanel ThirdLine;
    // End of variables declaration//GEN-END:variables
}
