/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculatorswingapp;

/**
 *
 * @author Eagle
 */
public class CalcForm extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public CalcForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ResultLine = new javax.swing.JPanel();
        ResultLabel = new javax.swing.JLabel();
        FirstLine = new javax.swing.JPanel();
        Num1 = new javax.swing.JButton();
        Num2 = new javax.swing.JButton();
        Num3 = new javax.swing.JButton();
        Plus = new javax.swing.JButton();
        SecondLine = new javax.swing.JPanel();
        Num4 = new javax.swing.JButton();
        Num5 = new javax.swing.JButton();
        Num6 = new javax.swing.JButton();
        Minus = new javax.swing.JButton();
        ThirdLine = new javax.swing.JPanel();
        Num7 = new javax.swing.JButton();
        Num8 = new javax.swing.JButton();
        Num9 = new javax.swing.JButton();
        Multiply = new javax.swing.JButton();
        FourthLine = new javax.swing.JPanel();
        Dot = new javax.swing.JButton();
        Num0 = new javax.swing.JButton();
        Equal = new javax.swing.JButton();
        Divide = new javax.swing.JButton();
        FifthLine = new javax.swing.JPanel();
        DefaultButton = new javax.swing.JButton();
        LeftPar = new javax.swing.JButton();
        RightPar = new javax.swing.JButton();
        NoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(350, 350));
        setMinimumSize(new java.awt.Dimension(350, 350));
        setPreferredSize(new java.awt.Dimension(350, 350));
        setSize(new java.awt.Dimension(350, 350));
        getContentPane().setLayout(new java.awt.GridLayout(6, 0));

        ResultLine.setBackground(new java.awt.Color(255, 255, 255));
        ResultLine.setToolTipText("");
        ResultLine.setAlignmentX(0.0F);
        ResultLine.setAutoscrolls(true);
        ResultLine.setMaximumSize(new java.awt.Dimension(300, 50));
        ResultLine.setMinimumSize(new java.awt.Dimension(300, 50));
        ResultLine.setPreferredSize(new java.awt.Dimension(300, 50));

        javax.swing.GroupLayout ResultLineLayout = new javax.swing.GroupLayout(ResultLine);
        ResultLine.setLayout(ResultLineLayout);
        ResultLineLayout.setHorizontalGroup(
            ResultLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ResultLabel)
        );
        ResultLineLayout.setVerticalGroup(
            ResultLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ResultLabel)
        );

        getContentPane().add(ResultLine);
        ResultLine.getAccessibleContext().setAccessibleName("");

        FirstLine.setAlignmentX(0.0F);
        FirstLine.setAlignmentY(1.0F);
        FirstLine.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        FirstLine.setMaximumSize(new java.awt.Dimension(450, 50));
        FirstLine.setMinimumSize(new java.awt.Dimension(450, 50));
        FirstLine.setName(""); // NOI18N
        FirstLine.setPreferredSize(new java.awt.Dimension(450, 50));

        Num1.setText("1");
        Num1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Num1MouseReleased(evt);
            }
        });
        Num1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Num1KeyReleased(evt);
            }
        });

        Num2.setText("2");
        Num2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Num2MouseReleased(evt);
            }
        });
        Num2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Num2KeyReleased(evt);
            }
        });

        Num3.setText("3");
        Num3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Num3MouseReleased(evt);
            }
        });
        Num3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Num3KeyReleased(evt);
            }
        });

        Plus.setText("+");
        Plus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                PlusMouseReleased(evt);
            }
        });
        Plus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PlusKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout FirstLineLayout = new javax.swing.GroupLayout(FirstLine);
        FirstLine.setLayout(FirstLineLayout);
        FirstLineLayout.setHorizontalGroup(
            FirstLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FirstLineLayout.createSequentialGroup()
                .addComponent(Num1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Num2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Num3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Plus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        FirstLineLayout.setVerticalGroup(
            FirstLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FirstLineLayout.createSequentialGroup()
                .addGroup(FirstLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Num3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(Num2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Num1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Plus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(244, 244, 244))
        );

        getContentPane().add(FirstLine);
        FirstLine.getAccessibleContext().setAccessibleName("");

        Num4.setText("4");

        Num5.setText("5");

        Num6.setText("6");

        Minus.setText("-");

        javax.swing.GroupLayout SecondLineLayout = new javax.swing.GroupLayout(SecondLine);
        SecondLine.setLayout(SecondLineLayout);
        SecondLineLayout.setHorizontalGroup(
            SecondLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SecondLineLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(Num4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Num5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Num6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Minus, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        SecondLineLayout.setVerticalGroup(
            SecondLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Num4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Num5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Num6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Minus, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(SecondLine);

        Num7.setText("7");

        Num8.setText("8");
        Num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Num8ActionPerformed(evt);
            }
        });

        Num9.setText("9");

        Multiply.setText("*");

        javax.swing.GroupLayout ThirdLineLayout = new javax.swing.GroupLayout(ThirdLine);
        ThirdLine.setLayout(ThirdLineLayout);
        ThirdLineLayout.setHorizontalGroup(
            ThirdLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThirdLineLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(Num7, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Num8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Num9, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ThirdLineLayout.setVerticalGroup(
            ThirdLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Num7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Num8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Num9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(ThirdLine);

        Dot.setText(".");

        Num0.setText("0");

        Equal.setText("=");

        Divide.setText("/");

        javax.swing.GroupLayout FourthLineLayout = new javax.swing.GroupLayout(FourthLine);
        FourthLine.setLayout(FourthLineLayout);
        FourthLineLayout.setHorizontalGroup(
            FourthLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FourthLineLayout.createSequentialGroup()
                .addComponent(Dot, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Num0, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Equal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Divide, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        FourthLineLayout.setVerticalGroup(
            FourthLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Equal, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
            .addComponent(Num0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Dot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Divide, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(FourthLine);

        DefaultButton.setText("C");

        LeftPar.setText("(");

        RightPar.setText(")");

        javax.swing.GroupLayout FifthLineLayout = new javax.swing.GroupLayout(FifthLine);
        FifthLine.setLayout(FifthLineLayout);
        FifthLineLayout.setHorizontalGroup(
            FifthLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FifthLineLayout.createSequentialGroup()
                .addComponent(DefaultButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(LeftPar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(RightPar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(NoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        FifthLineLayout.setVerticalGroup(
            FifthLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RightPar, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
            .addComponent(LeftPar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DefaultButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(NoButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(FifthLine);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Num8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Num8ActionPerformed

    private void Num1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Num1MouseReleased
        // TODO add your handling code here:
        setResultText(num1);
    }//GEN-LAST:event_Num1MouseReleased

    private void Num1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Num1KeyReleased
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if(ch == '1') {
            setResultText(num1);
        }
    }//GEN-LAST:event_Num1KeyReleased

    private void Num2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Num2KeyReleased
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if(ch == '2') {
            setResultText(num2);
        }
    }//GEN-LAST:event_Num2KeyReleased

    private void Num2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Num2MouseReleased
        // TODO add your handling code here:
        setResultText(num2);
    }//GEN-LAST:event_Num2MouseReleased

    private void Num3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Num3KeyReleased
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if(ch == '3') {
            setResultText(num3);
        }
    }//GEN-LAST:event_Num3KeyReleased

    private void Num3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Num3MouseReleased
        // TODO add your handling code here:
        setResultText(num3);
    }//GEN-LAST:event_Num3MouseReleased

    private void PlusKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PlusKeyReleased
        // TODO add your handling code here:
        char ch = evt.getKeyChar();
        if(ch == '+') {
            setResultText(plus);
        }
    }//GEN-LAST:event_PlusKeyReleased

    private void PlusMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlusMouseReleased
        // TODO add your handling code here:
        setResultText(plus);
    }//GEN-LAST:event_PlusMouseReleased

    private void setResultText(String s) {
        String currText = ResultLabel.getText();
        ResultLabel.setText(currText + s);
    }
    
    private final String num1 = "1";
    private final String num2 = "2";
    private final String num3 = "3";
    private final String num4 = "4";
    private final String num5 = "5";
    private final String num6 = "6";
    private final String num7 = "7";
    private final String num8 = "8";
    private final String num9 = "9";
    private final String num0 = "0";
    
    private final String plus = "+";
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DefaultButton;
    private javax.swing.JButton Divide;
    private javax.swing.JButton Dot;
    private javax.swing.JButton Equal;
    private javax.swing.JPanel FifthLine;
    private javax.swing.JPanel FirstLine;
    private javax.swing.JPanel FourthLine;
    private javax.swing.JButton LeftPar;
    private javax.swing.JButton Minus;
    private javax.swing.JButton Multiply;
    private javax.swing.JButton NoButton;
    private javax.swing.JButton Num0;
    private javax.swing.JButton Num1;
    private javax.swing.JButton Num2;
    private javax.swing.JButton Num3;
    private javax.swing.JButton Num4;
    private javax.swing.JButton Num5;
    private javax.swing.JButton Num6;
    private javax.swing.JButton Num7;
    private javax.swing.JButton Num8;
    private javax.swing.JButton Num9;
    private javax.swing.JButton Plus;
    private javax.swing.JLabel ResultLabel;
    private javax.swing.JPanel ResultLine;
    private javax.swing.JButton RightPar;
    private javax.swing.JPanel SecondLine;
    private javax.swing.JPanel ThirdLine;
    // End of variables declaration//GEN-END:variables
}
